const KEY='histoguia-integration-v1', THEME='histoguia-theme';
let state=JSON.parse(localStorage.getItem(KEY)||'{}');
let tab='home';
const $=s=>document.querySelector(s), screen=$('#screen');
const topicName=id=>DATA.topics.find(t=>t.id===id)?.name||id;
const phaseEpisodes=id=>DATA.episodes.filter(e=>e.phase_id===id);
const subEpisodes=id=>DATA.episodes.filter(e=>e.subperiod_id===id);
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function done(id){return !!state[id]?.done}
function toggleDone(id){state[id]={...(state[id]||{}),done:!done(id)};save();render()}
function counts(){let total=DATA.episodes.length, d=DATA.episodes.filter(e=>done(e.id)).length;return{total,d,pct:total?Math.round(d/total*100):0}}
function home(){let c=counts();screen.innerHTML=`<section class="card hero"><div><p class="overline">Gran Ruta de la Historia</p><h2>De la Prehistoria a nuestros días</h2><p class="meta">Prueba integrada: la app ya lee fases, subperiodos y episodios verificados.</p><div class="actions"><button class="primary" onclick="go('route')">Abrir ruta</button><button class="secondary" onclick="go('search')">Buscar episodios</button></div></div></section><section class="stats"><div class="stat"><b>${DATA.phases.length}</b><span>Fases</span></div><div class="stat"><b>${DATA.episodes.length}</b><span>Episodios</span></div><div class="stat"><b>${c.pct}%</b><span>Completado</span></div></section><div class="section-title"><h2>Primera fase activa</h2><p class="meta">Origen de la Humanidad ya tiene contenido de prueba.</p></div><section class="grid">${phaseCard(DATA.phases[0])}</section>`}
function phaseCard(p){let eps=phaseEpisodes(p.id);let locked=eps.length===0?' locked':'';return `<button class="phase${locked}" onclick="${eps.length?`openPhase('${p.id}')`:''}"><b>${String(p.order).padStart(2,'0')} · ${p.name}</b><span>${p.date_range} · ${eps.length} episodios verificados</span><p class="meta">${p.summary}</p></button>`}
function route(){screen.innerHTML=`<div class="section-title"><h2>La Gran Ruta</h2><p class="meta">Las fases sin episodios quedan atenuadas hasta que carguemos contenido verificado.</p></div><section class="grid">${DATA.phases.map(phaseCard).join('')}</section>`}
window.openPhase=id=>{let p=DATA.phases.find(x=>x.id===id);let subs=DATA.subperiods.filter(s=>s.phase_id===id);screen.innerHTML=`<button class="mini back" onclick="render()">← Volver</button><section class="card"><p class="overline">${p.date_range}</p><h2>${p.name}</h2><p class="meta">${p.summary}</p></section><div class="section-title"><h2>Subperiodos</h2></div><section class="grid">${subs.map(s=>subCard(s)).join('')}</section>`;window.scrollTo(0,0)}
function subCard(s){let eps=subEpisodes(s.id);return `<button class="subperiod ${eps.length?'':'locked'}" onclick="${eps.length?`openSub('${s.id}')`:''}"><b>${s.order}. ${s.name}</b><span>${s.date_range} · ${eps.length} episodios</span><p class="meta">${s.summary}</p></button>`}
window.openSub=id=>{let s=DATA.subperiods.find(x=>x.id===id), eps=subEpisodes(id);screen.innerHTML=`<button class="mini back" onclick="openPhase('${s.phase_id}')">← Volver</button><section class="card"><p class="overline">${s.date_range}</p><h2>${s.name}</h2><p class="meta">${s.summary}</p></section><div class="section-title"><h2>Episodios verificados</h2></div><section class="grid">${eps.map(episodeCard).join('')||'<div class="empty">Sin episodios aún.</div>'}</section>`;window.scrollTo(0,0)}
function episodeCard(e){return `<article class="episode"><p class="overline">${e.podcast_name}${e.episode_code?` · ${e.episode_code}`:''}</p><h3>${e.title}</h3><p class="meta">${topicName(e.main_topic_id)}${e.duration?` · ${e.duration}`:''}</p><p>${e.summary}</p><div class="tags"><span class="tag ok">Apple verificado</span><span class="tag">Prioridad ${e.priority}</span></div><div class="row"><a class="primary" href="${e.apple_url}" target="_blank">Abrir episodio</a><button class="secondary" onclick="toggleDone('${e.id}')">${done(e.id)?'Completado':'Marcar completado'}</button></div></article>`}
function search(){screen.innerHTML=`<input id="q" placeholder="Buscar: Neolítico, neandertales, evolución..."><section id="results" class="grid">${DATA.episodes.map(episodeCard).join('')}</section>`;$('#q').oninput=ev=>{let q=ev.target.value.toLowerCase();let res=DATA.episodes.filter(e=>(e.title+' '+e.summary+' '+topicName(e.main_topic_id)+' '+e.podcast_name).toLowerCase().includes(q));$('#results').innerHTML=res.map(episodeCard).join('')||'<div class="empty">Sin resultados.</div>'}}
function progress(){let c=counts();let phase=DATA.phases[0];let eps=phaseEpisodes(phase.id);let d=eps.filter(e=>done(e.id)).length;screen.innerHTML=`<section class="card"><p class="overline">Mi progreso</p><h2>${c.pct}% completado</h2><p class="meta">${c.d} de ${c.total} episodios marcados.</p></section><div class="section-title"><h2>Por fase</h2></div><section class="grid"><article class="phase"><b>${phase.name}</b><span>${d}/${eps.length} episodios</span></article></section>`}
function render(){if(tab==='home')home();if(tab==='route')route();if(tab==='search')search();if(tab==='progress')progress()}
window.go=t=>{tab=t;activate();render()}
function activate(){document.querySelectorAll('.bottom button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab))}
document.querySelectorAll('.bottom button').forEach(b=>b.onclick=()=>go(b.dataset.tab));
if(localStorage.getItem(THEME)==='light')document.documentElement.classList.add('light');
$('#themeBtn').onclick=()=>{document.documentElement.classList.toggle('light');localStorage.setItem(THEME,document.documentElement.classList.contains('light')?'light':'dark')};
render();