const KEY='histoguia-cards-v2', THEME='histoguia-theme';
let state=JSON.parse(localStorage.getItem(KEY)||'{}');
let tab='home';
const $=s=>document.querySelector(s), screen=$('#screen');
const topicName=id=>DATA.topics.find(t=>t.id===id)?.name||id;
const subName=id=>DATA.subperiods.find(s=>s.id===id)?.name||id;
const phaseEpisodes=id=>DATA.episodes.filter(e=>e.phase_id===id);
const subEpisodes=id=>DATA.episodes.filter(e=>e.subperiod_id===id);
function save(){localStorage.setItem(KEY,JSON.stringify(state))}
function done(id){return !!state[id]?.done}
function fav(id){return !!state[id]?.fav}
function toggleDone(id){state[id]={...(state[id]||{}),done:!done(id)};save();render()}
function toggleFav(id){state[id]={...(state[id]||{}),fav:!fav(id)};save();render()}
function counts(){let total=DATA.episodes.length, d=DATA.episodes.filter(e=>done(e.id)).length;return{total,d,pct:total?Math.round(d/total*100):0,f:DATA.episodes.filter(e=>fav(e.id)).length}}
function home(){let c=counts();screen.innerHTML=`<section class="card hero"><div><p class="overline">Gran Ruta de la Historia</p><h2>Aprende Historia por rutas, temas y episodios</h2><p class="meta">Nueva prueba: cada episodio tiene ficha enciclopédica, plataformas y contexto histórico.</p><div class="actions"><button class="primary" onclick="go('route')">Abrir ruta</button><button class="secondary" onclick="go('search')">Buscar</button></div></div></section><section class="stats"><div class="stat"><b>${DATA.phases.length}</b><span>Fases</span></div><div class="stat"><b>${DATA.episodes.length}</b><span>Episodios</span></div><div class="stat"><b>${c.pct}%</b><span>Completado</span></div></section><div class="section-title"><h2>Recomendado para empezar</h2><p class="meta">Episodios con prioridad 3.</p></div><section class="grid">${DATA.episodes.filter(e=>e.priority===3).map(episodeCard).join('')}</section>`}
function phaseCard(p){let eps=phaseEpisodes(p.id);let locked=eps.length===0?' locked':'';return `<button class="phase${locked}" onclick="${eps.length?`openPhase('${p.id}')`:''}"><b>${String(p.order).padStart(2,'0')} · ${p.name}</b><span>${p.date_range} · ${eps.length} episodios</span><p class="meta">${p.summary}</p></button>`}
function route(){screen.innerHTML=`<div class="section-title"><h2>La Gran Ruta</h2><p class="meta">Cada fase se irá activando al cargar episodios verificados.</p></div><section class="grid">${DATA.phases.map(phaseCard).join('')}</section>`}
window.openPhase=id=>{let p=DATA.phases.find(x=>x.id===id);let subs=DATA.subperiods.filter(s=>s.phase_id===id);screen.innerHTML=`<button class="mini back" onclick="render()">← Volver</button><section class="card"><p class="overline">${p.date_range}</p><h2>${p.name}</h2><p class="meta">${p.summary}</p></section><div class="section-title"><h2>Subperiodos</h2></div><section class="grid">${subs.map(subCard).join('')}</section>`;window.scrollTo(0,0)}
function subCard(s){let eps=subEpisodes(s.id);return `<button class="subperiod ${eps.length?'':'locked'}" onclick="${eps.length?`openSub('${s.id}')`:''}"><b>${s.order}. ${s.name}</b><span>${s.date_range} · ${eps.length} episodios</span><p class="meta">${s.summary}</p></button>`}
window.openSub=id=>{let s=DATA.subperiods.find(x=>x.id===id), eps=subEpisodes(id);screen.innerHTML=`<button class="mini back" onclick="openPhase('${s.phase_id}')">← Volver</button><section class="card"><p class="overline">${s.date_range}</p><h2>${s.name}</h2><p class="meta">${s.summary}</p></section><div class="section-title"><h2>Episodios</h2></div><section class="grid">${eps.map(episodeCard).join('')||'<div class="empty">Sin episodios aún.</div>'}</section>`;window.scrollTo(0,0)}
function episodeCard(e){return `<article class="episode"><p class="overline">${e.podcast_name}${e.episode_code?` · ${e.episode_code}`:''}</p><h3>${e.title}</h3><p class="meta">${topicName(e.main_topic_id)}${e.duration?` · ${e.duration}`:''}</p><p>${e.summary}</p><div class="tags"><span class="tag ok">Apple verificado</span><span class="tag">Prioridad ${e.priority}</span>${done(e.id)?'<span class="tag ok">Completado</span>':''}</div><div class="row"><button class="primary" onclick="openEpisode('${e.id}')">Ver ficha</button><button class="secondary" onclick="toggleDone('${e.id}')">${done(e.id)?'Completado':'Marcar completado'}</button></div></article>`}
window.openEpisode=id=>{let e=DATA.episodes.find(x=>x.id===id);screen.innerHTML=episodeDetail(e);window.scrollTo(0,0)}
function episodeDetail(e){let platforms=[['Apple Podcasts',e.apple_url,'apple'],['Spotify',e.spotify_url,''],['iVoox',e.ivoox_url,''],['YouTube',e.youtube_url,''],['Web',e.web_url,'']];return `<button class="mini back" onclick="render()">← Volver</button><section class="card"><p class="overline">${e.podcast_name}${e.episode_code?` · ${e.episode_code}`:''}</p><h2>${e.title}</h2><p class="meta">${topicName(e.main_topic_id)} · ${subName(e.subperiod_id)}${e.duration?` · ${e.duration}`:''}</p><div class="tags"><span class="tag ok">Apple verificado</span><span class="tag warn">No garantiza apertura directa en app</span><span class="tag">Prioridad ${e.priority}</span></div><p>${e.summary}</p><div class="section-title"><h3>Qué aprenderás</h3></div><ul class="learn">${(e.learn||[]).map(x=>`<li>${x}</li>`).join('')}</ul><div class="section-title"><h3>Valoración editorial</h3></div><div class="score"><div><b>${'★'.repeat(e.priority)}</b><br><span class="small">Prioridad</span></div><div><b>${'★'.repeat(e.difficulty)}</b><br><span class="small">Dificultad</span></div><div><b>${'★'.repeat(e.depth)}</b><br><span class="small">Profundidad</span></div></div><div class="section-title"><h3>Escúchalo en</h3><p class="meta">Apple puede abrir el episodio o el programa según iOS; mantenemos otras plataformas preparadas.</p></div><div class="links">${platforms.map(p=>p[1]?`<a class="platform ${p[2]}" href="${p[1]}" target="_blank">${p[0]}</a>`:`<span class="platform disabled">${p[0]} · pendiente</span>`).join('')}</div><div class="section-title"><h3>Relacionado</h3></div><div class="pills">${(e.related_topics||[]).map(x=>`<span class="pill">${x}</span>`).join('')}</div><div class="actions"><button class="secondary" onclick="toggleFav('${e.id}')">${fav(e.id)?'Quitar favorito':'Añadir favorito'}</button><button class="secondary" onclick="toggleDone('${e.id}')">${done(e.id)?'Completado':'Marcar completado'}</button></div></section>`}
function search(){screen.innerHTML=`<input id="q" placeholder="Buscar: Neolítico, neandertales, evolución..."><section id="results" class="grid">${DATA.episodes.map(episodeCard).join('')}</section>`;$('#q').oninput=ev=>{let q=ev.target.value.toLowerCase();let res=DATA.episodes.filter(e=>(e.title+' '+e.summary+' '+topicName(e.main_topic_id)+' '+e.podcast_name+' '+(e.related_topics||[]).join(' ')).toLowerCase().includes(q));$('#results').innerHTML=res.map(episodeCard).join('')||'<div class="empty">Sin resultados.</div>'}}
function progress(){let c=counts();let favs=DATA.episodes.filter(e=>fav(e.id));screen.innerHTML=`<section class="card"><p class="overline">Mi progreso</p><h2>${c.pct}% completado</h2><p class="meta">${c.d} de ${c.total} episodios marcados. ${c.f} favoritos.</p></section><div class="section-title"><h2>Favoritos</h2></div><section class="grid">${favs.map(episodeCard).join('')||'<div class="empty">Sin favoritos aún.</div>'}</section>`}
function render(){if(tab==='home')home();if(tab==='route')route();if(tab==='search')search();if(tab==='progress')progress()}
window.go=t=>{tab=t;activate();render()}
function activate(){document.querySelectorAll('.bottom button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab))}
document.querySelectorAll('.bottom button').forEach(b=>b.onclick=()=>go(b.dataset.tab));
if(localStorage.getItem(THEME)==='light')document.documentElement.classList.add('light');
$('#themeBtn').onclick=()=>{document.documentElement.classList.toggle('light');localStorage.setItem(THEME,document.documentElement.classList.contains('light')?'light':'dark')};
render();